baseURL = 'https://super-gumdrop-60116b.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke_custom'

[taxonomies]
	category = 'categories'
	tag = 'tags'
	author = 'author'

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[[menu.main]]
    name = 'Authors'
    pageRef = '/author'
    weight = 30

[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[[menu.main]]
    name = 'Infographics'
    pageRef = '/tags/infographic'
    weight = 50

[[menu.main]]
    name = 'ICT in the News'
    pageRef = '/tags/ict-in-the-news'
    wight = 60

[[menu.main]]
   name = 'Issue Introductions'
   pageRef = '/tags/issue-introductions'
   weight = 70